"""Persistent priors — ``DACLI.md`` (workstream 2.6).

The CLAUDE.md analogue: a project-root markdown file holding durable,
user-authored priors — connection profiles, naming conventions, the medallion
rules that used to be hardcoded in the system prompt. Loaded once at session
start as the **top layer of context** (owns full context assembly;
 just makes the priors *data*, not prompt hardcoding).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

# Project-root priors file.
DACLI_PRIORS_FILE = Path("DACLI.md")


def find_priors_file(start: Path | None = None) -> Path | None:
    """Locate ``DACLI.md`` by walking up from ``start`` to the filesystem root."""
    current = (start or Path.cwd()).resolve()
    for directory in [current, *current.parents]:
        candidate = directory / DACLI_PRIORS_FILE.name
        if candidate.exists():
            return candidate
    return None


def load_priors(path: str | None = None) -> str:
    """Return the priors markdown, or an empty string if none exists."""
    target = Path(path) if path else find_priors_file()
    if target and target.exists():
        try:
            return target.read_text(encoding="utf-8").strip()
        except Exception:
            return ""
    return ""


# ---------------------------------------------------------------------------
# Draft generation (the `/init` command)
# ---------------------------------------------------------------------------
def _connection_profiles(settings: Any) -> list[str]:
    """Build the Connection Profiles section from **non-secret** config only.

    Reads structural fields (database, schema, warehouse, role, repo, index)
    and never touches passwords, API keys, tokens, or account/user identifiers.
    """
    blocks: list[str] = []

    sf = getattr(settings, "snowflake", None)
    if sf and getattr(sf, "database", ""):
        lines = [f"  - Database: `{sf.database}`"]
        schema = getattr(sf, "db_schema", "") or "PUBLIC"
        lines.append(f"  - Default schema: `{sf.database}.{schema}`")
        if getattr(sf, "warehouse", ""):
            lines.append(f"  - Warehouse: `{sf.warehouse}`")
        if getattr(sf, "role", ""):
            lines.append(f"  - Role: `{sf.role}`")
        blocks.append("- **Snowflake**\n" + "\n".join(lines))

    gh = getattr(settings, "github", None)
    if gh and getattr(gh, "owner", "") and getattr(gh, "repo", ""):
        lines = [f"  - Repository: `{gh.owner}/{gh.repo}`"]
        if getattr(gh, "branch", ""):
            lines.append(f"  - Branch: `{gh.branch}`")
        blocks.append("- **GitHub**\n" + "\n".join(lines))

    pc = getattr(settings, "pinecone", None)
    if pc and getattr(pc, "index_name", ""):
        lines = [f"  - Index: `{pc.index_name}`"]
        if getattr(pc, "environment", ""):
            lines.append(f"  - Environment: `{pc.environment}`")
        blocks.append("- **Pinecone (docs search)**\n" + "\n".join(lines))

    if not blocks:
        blocks.append(
            "- _No connectors configured yet. Run `dacli setup`, then `/init` "
            "again to populate this section._"
        )
    return blocks


def generate_dacli_md(settings: Any) -> str:
    """Render a DACLI.md draft. Connection profiles come from config (no secrets);
    the conventions/rules below are editable defaults."""
    profiles = "\n\n".join(_connection_profiles(settings))
    return f"""# DACLI Priors

Durable, user-authored priors for this project — the CLAUDE.md analogue. This
file is loaded once at session start as the **top layer of context**. Edit it to
teach the agent your conventions; they become *data*, not prompt hardcoding.

> This draft was generated by `/init` from your `config.yaml`. Connection
> profiles list only non-secret structural details (no passwords/keys/tokens).
> Review and edit freely.

> Confidence note: the agent treats these as high-trust priors, but facts about
> *live systems* (which schemas/tables actually exist) are always re-verified
> against the catalog before risky actions — priors describe intent and
> conventions, not the current live state.

---

## Connection Profiles

{profiles}

---

## Medallion Architecture

- **Bronze (Snowflake native):** build all infrastructure from scratch —
  schemas, file formats, tables. Load raw data from stages into Bronze tables
  with `COPY INTO`. Bronze tables are the sources for dbt.
- **Silver & Gold (dbt via GitHub Actions):** push dbt model SQL to the repo,
  create/update workflows, trigger runs (`dbt run` / `dbt test`), and verify.

---

## Naming & Modeling Conventions

- Always use fully-qualified names: `DATABASE.SCHEMA.OBJECT`.
- Use `CREATE OR REPLACE` or `CREATE IF NOT EXISTS` for idempotency.
- Include metadata columns in every Bronze table; cast columns in `COPY INTO`.

---

## Operating Rules

1. **One SQL statement per execution.** Never batch multiple statements in one
   tool call.
2. **File formats**
   - `SKIP_HEADER` and `PARSE_HEADER` are mutually exclusive.
   - `PARSE_HEADER = TRUE` is ONLY for `INFER_SCHEMA` / `MATCH_BY_COLUMN_NAME`.
   - Do NOT use a `PARSE_HEADER = TRUE` format in `SELECT` statements — it raises
     `002005 (42601)`. Use a standard `CSV_FORMAT` (`PARSE_HEADER = FALSE`) for
     querying/previewing.
3. **Querying staged files**
   - Never `SELECT *` on CSVs — use `SELECT $1, $2, ...`.
   - Prefer named file formats over inline definitions.
4. **GitHub Actions workflows**
   - Workflows must have ONLY the `workflow_dispatch` trigger.
   - Never use `on: push` or `on: schedule` — the agent triggers manually.
5. **dbt sources**
   - Each source name must be UNIQUE across all schema files.
   - Define sources ONCE (recommended: `models/sources.yml`).
6. **Python package installation**
   - Do NOT pin versions in `pip install`; use unpinned names.
7. **Data display — no truncation, no summaries**
   - Never truncate, sample, or summarize returned data. The CLI renders every
     tool result as a full, formatted table. Do not abbreviate rows
     (`… N more`) or re-print large tables in prose; report the row count and
     real analysis instead.

---

## Error Handling

- On error: stop, report it, do not retry with modified syntax. Use
  `request_user_input` for guidance and `search_snowflake_docs` for reference.
"""
