version: 2

sources:
  - name: bronze
    schema: BRONZE
    tables:
      - name: cust_az12
      - name: loc_a101
      - name: px_cat_g1v2
      - name: cust_info
      - name: prd_info
      - name: sales_details